### ISSUE TITLE
Always getting Invalid State on login or signup

### ISSUE THREAD

**Issue by gnorbsl** [auth0-samples/auth0-laravel-php-web-app#50] opened 2020-12-14 10:06 UTC
Hi,

I first followed your guide on my own laravel project and got an invalid state error, then I just downloaded this sample and I still get the invalid state error.

I triple checked that I have these fields in my settings 

    http://localhost:3000/auth0/callback to the Allowed Callback URLs field
    http://localhost:3000 to the Allowed Web Origins field
    http://localhost:3000 to the Allowed Logout URLs field

The env is loaded properly

I can't figure out whats missing, and the docs for that issue seem to be no help at all.

Any insight would be appreciated.

**Comment by gnorbsl** [comment] 2020-12-14 11:11
So it seems this issue appears and disappears and it's hard to reproduce. It randomly stops working, then I reserve again and it works, then it stops working again on next serve.

**Comment by evansims** [comment] 2020-12-14 14:32
Hey @gnorbsl 👋 Sorry you're having trouble on this! This is a little bit of a tough one to track down, but let's see what we can do.

Could you tell me what version of PHP and Laravel you're running? Also, what browser are you seeing this in, and are you running any plugins or browser settings that could be interfering with cookies? In my experience invalid state errors most often pop up because of issues around cookie handling

**Comment by evansims** [comment] 2021-02-16 23:20
Closing this for now; feel free to reopen if you're continuing to have issues on this.

**Closed by evansims** 2021-02-16 23:20 UTC

**Comment by kingRayhan** [comment] 2022-03-15 22:45
I am facing the same issue, It can not be reproduced but it's occurring sometimes.
